# src/synthesis/phonebook_generator.py

"""
Synthetic data generator dedicated to PhoneBook.
Generates QA pairs using a rule-based approach and converts them into PnP/NTP training formats.
"""

import logging
from typing import List, Dict, Any

class PhoneBookSynthesizer:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.training_method = config['training']['method']  # 'dcd' or 'ntp'
        self.context_mode = config.get('dataset', {}).get('context_mode', 'full')
        
    def synthesize_for_chunk(self, data_point: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Generates training samples from a single data point.
        
        Args:
            data_point: A single QA sample generated by PhoneBookLoader.
            
        Returns:
            List[Dict]: Samples to be used for training.
        """
        question = data_point['question']
        answer = data_point['target_answer']
        context = data_point['context']
        
        # Strict prompt format (Answer only contains the phone number)
        qa_text = f"Question: {question}\nAnswer: {answer}"
        
        if self.training_method == 'dcd':
            # PnP/DCD format: Separate context and synthetic_sample
            return [{
                'context': context,  # Context for the Teacher
                'synthetic_sample': qa_text,  # QA for the Student to learn
                'type': 'phonebook_qa',
                'metadata': data_point['metadata']
            }]
        
        elif self.training_method == 'ntp':
            # NTP format: Train on QA only (no context)
            return [{
                'text': qa_text,  # NTP uses the 'text' key
                'type': 'phonebook_qa',
                'metadata': data_point['metadata']
            }]
        
        else:
            raise ValueError(f"Unsupported training method: {self.training_method}")
    
    def prepare_batch_data(self, data_points: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Process multiple data points in a batch.
        
        Args:
            data_points: List of QA samples generated by PhoneBookLoader.
            
        Returns:
            List[Dict]: All training samples.
        """
        all_samples = []
        for data_point in data_points:
            samples = self.synthesize_for_chunk(data_point)
            all_samples.extend(samples)
        
        logging.info(f"Generated a total of {len(all_samples)} training samples. (Method: {self.training_method})")
        return all_samples